# **Pytorch fundamentals**

pytorch is an sopen source machine learning framework primarily used for developing and training deep learning models based on artifical neural network it was developed by meta in 2016



In [ ]:
print("Hello pytorch")

Hello pytorch


In [ ]:
!nvidia-smi

Sun Jul 13 04:56:34 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   51C    P8             10W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


# introduction to tensors

In [ ]:

# creating tensors
# scalar quantity is nothing more than an integer with only one magnitude

scalar = torch.tensor(7)
scalar

scalar.ndim
# get tensor back
scalar.item()

#vector
#A vector is a special type of tensor, specifically a first-order tensor,
#that represents a quantity with both magnitude and direction

vector=torch.tensor([7,7])
vector
vector.ndim
vector.shape


# matrix
matrix=torch.tensor([[7,8],[9,10]])
matrix
matrix.ndim
matrix[1][0]
matrix.shape


#tensor
tensor=torch.tensor([[[1,2,3],[3,6,9],[2,4,5]]])
tensor
tensor.ndim
tensor.shape
tensor[0]

tensor(7)

# Random tensors

why random tensors?

##### Random tensors are important because the way many neaural networks learn is they start with tensors full of random numberes and then adjust those numbers to better represent data

In [ ]:
# create a random tensors
random_tensor=torch.rand(3,4,4)
random_tensor

random_tensor.shape
random_tensor.ndim
#create random with similar shape to an image tensor
random_size =torch.rand(size=(224,224,3)) # height, width, colour channel(R,G,B)
random_size.ndim

random_size.shape

tensor([[[0.2380, 0.2469, 0.3757, 0.6847],
         [0.7951, 0.3315, 0.2635, 0.1111],
         [0.8087, 0.7189, 0.4004, 0.0467],
         [0.6654, 0.6016, 0.9005, 0.9870]],

        [[0.7013, 0.6236, 0.9832, 0.6981],
         [0.2515, 0.6293, 0.7058, 0.4016],
         [0.8555, 0.6294, 0.0465, 0.8154],
         [0.3569, 0.8575, 0.1920, 0.9024]],

        [[0.5490, 0.6364, 0.9703, 0.5752],
         [0.5154, 0.1068, 0.5924, 0.6991],
         [0.9656, 0.4076, 0.8842, 0.8736],
         [0.5663, 0.7996, 0.5689, 0.3279]]])

# Most common error in a tensor

there are mainly 3 common errors can be araised while working with tensors

1.Data type error where there is an change in data types between two tensors can cause an error

2.size of an tensor can cause while multiplying with other tensors

3.device of the tensor where it runs

# Zeroes and ones

In [ ]:
# create zeroes and ones
zero=torch.zeros(size=(3,4))
zero

ones=torch.ones(size=(3,4))
ones

ones.dtype

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

# create a name of tensors


In [ ]:
#use torch.arange to create a range of tensors
torch.arange(start=1,end=11,step=1)

# create tensors like
input=torch.arange(start=1,end=11,step=1)

ten_zeros=torch.zeros_like(input)
ten_zeros

ten_ones =torch.ones_like(input=ten_zeros)
ten_ones

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# Tensor Datatypes

In [ ]:
#create a tensor with an data type
float_32_tensor = torch.tensor([3.0,4.0,5.0,6.0],
                               dtype=torch.float32, # datatype of tensors to calculate the precision in computing
                               device=None, # can be used to convert to gpu to run the code by using CUDA can be changed to cpu
                               requires_grad=False) # used to calculating and tracking the gradients
float_32_tensor
float_32_tensor.dtype

# precision is nothing storing the tensor in computer memory
float_32_tensor.dtype
print(f"device of the tensor :{tensor.device}")


torch.float32

# manipulating Tensors


In [ ]:
# Tensor operations :
# matrix multiplications

# create a tensor
tensor = torch.tensor([1,2,3])
tensor+10


# multiply tensor
tensor * 10
tensor
torch.add(tensor,10)
torch.mul(tensor,10)
torch.div(tensor,10)
torch.sub(tensor,10)


# matrxi multiplications

# two ways to perform multiplications

# 1. element waitstatus_to_exitcode
# 2. matrix matrix by another matrix (dot product)

# elemrnt wise multiplication

print(tensor,"*",tensor)
tensor * tensor

# matrix multiplications
torch.matmul(tensor,tensor) # dot product

# matrix mul by normal
1*1 + 2*2 + 3*3


%%time
value =0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)


%%time
torch.matmul(tensor,tensor) # dot product
# common error in multiplication matrix
# two rules to satisfy for matrix multiplication

# 1.**inner dimmensions must match**
# (3,2) @ (3,2) wont work
# (2,3) @ (3,2) will work
# (3,2) @ (2,3) will work


# 2.**the resulting matrix has the shape of the outer dimension**
# (2,3)@(3,2) -> (2,2)
# (3,2)@(2,3) ->(3,3)


torch.matmul(torch.rand(2,3),torch.rand(3,2))
# shapes for matrix multiplictions
tensor_A=torch.tensor([[1,2],
                       [3,4],
                       [5,6]])

tensor_b=torch.tensor([[7,10],
                       [8,11],
                       [9,12]])


torch.mm(tensor_A,tensor_b) # torch.mm is the same as torch.matmul
tensor_A.shape,tensor_b.shape

# to fix shape issues we can manipulate the shape of one of tensor using transpose

# transpose used to switches the axies or dimensions of a given tensors
tensor_b.T


tensor_b
# matrix multipliction operation works tensor_b is transposed


torch.mm(tensor_A,tensor_b.T) # T is transpose
tensor.shape

tensor([11, 12, 13])

### Finding the tensor aggregation min, max, sum, mean etc

In [ ]:
# finding a tensor
x=torch.arange(0,10,1)
x

#finding a min
torch.min(x), x.min()

#finding a max
torch.max(x), x.max()

# finding a mean for torch.mean() it requiers a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

#find sum
torch.sum(x), x.sum()

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# finding the positional min and max

In [ ]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# find the position in tensor that has the minimum value with argmin() return index of the value
x.argmin()

tensor(0)

In [ ]:
# find the max value of the maximum value with argmax() return index of the value
x.argmax()

tensor(9)

# reshaping , stacking , squeezing and un squeezing tensors

* reshapeing : reshape input tensor to a defined shape


* view : return a view of an input tensor of certain shape but keep the same memory as the original tensor


* stacking : combine multiple tensors on top of each other (vstack) or side by side (hstack)


* squeeze : removes all 1 dimensions from a tensor


* unsqueeze : add a 1 dimension to a target tensor


* permute : return a view of the input with dimensions permuted (swapped) in a certain way





In [ ]:
import torch
x=torch.arange(1,10);
x,x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [ ]:
# add extra dimensions
x_reshape =x.reshape(1,9) # changing the shape of the tensors
# add extra dimensions
x_reshape =x.reshape(3,3) # changing the shape of the tensors
x_reshape,x_reshape.shape

(tensor([[5, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 torch.Size([3, 3]))

In [ ]:
z=x.view(1,9)
z,z.shape



(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [ ]:
x

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# changing z changes x (because a view of a tensor shares the same memory of the orginal)
z[:,0]=5
z, x

(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]), tensor([5, 2, 3, 4, 5, 6, 7, 8, 9]))

In [ ]:
# stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x],dim=1)
x_stacked

tensor([[5, 5, 5, 5],
        [2, 2, 2, 2],
        [3, 3, 3, 3],
        [4, 4, 4, 4],
        [5, 5, 5, 5],
        [6, 6, 6, 6],
        [7, 7, 7, 7],
        [8, 8, 8, 8],
        [9, 9, 9, 9]])

In [ ]:
# squeezing and unsquuezing
x.squeeze() # removes all single dimensions from target tensors


tensor([5, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x.shape

torch.Size([9])

In [ ]:
x.unsqueeze(dim=0) # adds a single dimension to a target tensor at a specific dim

tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]])

In [ ]:
x.shape

torch.Size([9])

In [ ]:
# permute - rearrange the dimensions of a target tensor in a specific order
x_orginal = torch.rand(size=(224,224,3)) # height, width, colour channel

#permute orginal tensor to rearrange the axis order
x_permuted = x_orginal.permute(2,0,1) # shifts axis 0->1, 1->2, 2->0


In [ ]:
x_orginal.shape, x_permuted.shape

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

In [ ]:
x_orginal[0, 0, 0] = 234


In [ ]:
x_orginal, x_permuted # permute

(tensor([[[2.3400e+02, 4.7866e-01, 6.2784e-01],
          [2.3400e+02, 2.5410e-01, 8.3367e-01],
          [2.3400e+02, 2.8688e-01, 1.9612e-01],
          ...,
          [2.3400e+02, 9.2467e-01, 6.1643e-01],
          [2.3400e+02, 3.6710e-01, 5.0416e-01],
          [2.3400e+02, 1.5162e-01, 4.8700e-01]],
 
         [[2.3400e+02, 1.0658e-01, 8.6681e-01],
          [2.3400e+02, 7.0935e-01, 1.3886e-02],
          [2.3400e+02, 1.3593e-01, 3.6184e-01],
          ...,
          [2.3400e+02, 5.8188e-01, 4.5635e-01],
          [2.3400e+02, 5.1025e-01, 8.1207e-01],
          [2.3400e+02, 9.8226e-01, 2.6833e-01]],
 
         [[2.3400e+02, 7.6508e-01, 3.2351e-01],
          [2.3400e+02, 6.1307e-01, 8.2422e-01],
          [2.3400e+02, 4.0002e-01, 9.5718e-01],
          ...,
          [2.3400e+02, 7.6910e-01, 2.1592e-01],
          [2.3400e+02, 3.4063e-01, 4.4004e-01],
          [2.3400e+02, 7.4564e-02, 6.3152e-01]],
 
         ...,
 
         [[2.3400e+02, 2.2112e-01, 8.2465e-01],
          [2.3400e

# indexing (selecting data from tensors)


*  indexing with pytorch is similar to Numpy



In [4]:
#create a tensor
import torch
x=torch.arange(1,10).reshape(1,3,3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [5]:
# index on tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [6]:
x[0][0]

tensor([1, 2, 3])

In [7]:
x[0][0][0]

tensor(1)

In [10]:
x[:,0]

tensor([[1, 2, 3]])

In [12]:
x[:,:,1]

tensor([[2, 5, 8]])

# pytorch tensors and Numpy

numpy is a popular scientific python numerical computing torch.library
pytorch has functionality to interact with it


In [13]:
#numpy array to tensor
import torch
import numpy as np

array =np.arange(1.0,8.0)
tensor = torch.from_numpy(array)
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [14]:
array.dtype

dtype('float64')

In [18]:
torch.arange(1.0,8.0).dtype

torch.float32

In [20]:
# tensor to numpy array
tensor=torch.ones(7)
numpy_tensor=tensor.numpy()
tensor,numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

# reproducbility of pytorch

In [21]:
# to reduce the randomness in neural networks and pytorch comes the concept of a random seed

# random seed : a number used to initialize a pseudorandom number generator
import torch

random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)


print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.4222, 0.7105, 0.3533, 0.2797],
        [0.7962, 0.2868, 0.3150, 0.0075],
        [0.0663, 0.8717, 0.0478, 0.9955]])
tensor([[0.5845, 0.3421, 0.5454, 0.4578],
        [0.3677, 0.3075, 0.5214, 0.6255],
        [0.2935, 0.7358, 0.4026, 0.2369]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [26]:
# let make a random reproducible tensor
import torch

torch.manual_seed(42)

random_tensor_C = torch.rand(3,4)

torch.manual_seed(42) # produces the same random values of different tensor
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


#running tensors and pytorch objects in gpu

gpu =faster computation on numbers, thanks to CUDA + NVIDIA hardware accelerator

In [ ]:
# setup a gpu in colab

In [1]:
!nvidia-smi

Mon Jul 14 06:19:27 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   64C    P8             10W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [2]:
## check for gpu access with pytorch
import torch
torch.cuda.is_available()

True

In [3]:
# setup device agnostic code
device ="cuda"
if torch.cuda.is_available():
  device = torch.device("cuda")
else:
  device = torch.device("cpu")
  print("not available")

In [4]:
device

device(type='cuda')

In [5]:
#count number of devices
torch.cuda.device_count()

1

In [3]:
#putting tensors on gpu
tensor =torch.tensor([1,2,3])

print(tensor,tensor.device)


tensor([1, 2, 3]) cpu


In [5]:
# move tensor to gpu
device="cuda"
tensor_to_device =tensor.to(device)
tensor_to_device

tensor([1, 2, 3], device='cuda:0')

In [10]:
# tensors back to cpu

tensor_to_device.cpu().numpy()

tensor([1, 2, 3])

In [11]:
tensor_to_device.dtype

torch.int64